server:
  port: 1003
 
spring:
  application:
    name: FriendFamilyMS
  cloud:
    consul:
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefixes:
        -  config
        default-context: application
        profile-separator: '::'
        format: YAML
  config:
    import: 'consul:'   