
 
resilience4j:
  circuitbreaker:
    instances:
      friendFamilyService:
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        
spring:
  application:
    name: FriendFamilyMS
  cloud:
    consul:
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefixes:
        -  config
        default-context: application
        profile-separator: '::'
        format: YAML
  config:
    import: 'consul:'   