server:
  port: 1001

resilience4j:
  circuitbreaker:
    instances:
      callDetailsService:
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
      
      
spring:
  application:
    name: CallDetailsMS
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefixes:
        -  config
        default-context: application
        profile-separator: '::'
        format: YAML
  config:
    import: 'consul:'
      
      
      
      