server:
  port: 5001
      
spring:
  application:
    name: gatewayMS
  cloud:
    consul:
      config:
        data-key: data
        prefixes:
        - config
        format: yaml
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: CallDetailsMS
        uri: lb://CallDetailsMS
        predicates:
        - Path=/calldetails/**
        filters:
        - APIGatewayFilter
      - id: CustomerMS
        uri: lb://CustomerMS
        predicates:
        - Path=/customer/**
        filters:
        - APIGatewayFilter
      - id: FriendFamilyMS
        uri: lb://FriendFamilyMS
        predicates:
        - Path=/friendfamily/**
        filters:
        - APIGatewayFilter
      - id: PlanMS
        uri: lb://PlanMS
        predicates:
        - Path=/plan/**
        filters:
        - APIGatewayFilter
      - id: SecurityMS
        uri: lb://SecurityMS
        predicates:
        - Path=/login
        filters:
        - APIGatewayFilter
          
          
       
  config:
    import: 'consul:'
    