server:
  port: 0
      
spring:
  application:
    name: SecurityMS
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
       enabled: true
       prefixes:
       -  config
       default-context: application
       profile-separator: '::'
       format: YAML
   
  config:
    import: 'consul:'