server:
  port: 0
      
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  application:
    name: SecurityMS
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
       enabled: true
       prefixes:
       -  config
       default-context: application
       profile-separator: '::'
       format: YAML
   
  config:
    import: 'consul:'