server:
  port: 1004
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*' 
spring:
  application:
    name: PlanMS
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefixes:
        -  config
        default-context: application
        profile-separator: '::'
        format: YAML
  config:
    import: 'consul:'
    