server:
  port: 1004
 
spring:
  application:
    name: PlanMS
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefixes:
        -  config
        default-context: application
        profile-separator: '::'
        format: YAML
  config:
    import: 'consul:'
    